#!/bin/bash
# Stop hook — auto-commit my-ai-agents snapshot when Claude/ changes.
# Mirror-only, no push. Commit message is generated by `claude --print --bare`
# from the actual diff so it reflects intent, not a generic "auto-sync" stamp.
# If message generation fails or doesn't match conventional-commits, the hook
# un-stages and exits 0 — leaving the work for the user to commit manually.

set -uo pipefail

REPO=/Users/mian.yang/Repos/my-ai-agents
LOG=/Users/mian.yang/.claude/sync-to-snapshot.log

cd "$REPO" 2>/dev/null || exit 0

# Nothing to commit under Claude/ → silent no-op
[ -z "$(git status --porcelain Claude/)" ] && exit 0

# Skip mid-operation states
{ [ -d .git/rebase-merge ] || [ -d .git/rebase-apply ] || \
  [ -f .git/MERGE_HEAD ] || [ -f .git/CHERRY_PICK_HEAD ]; } && {
  printf '%s [SKIP] mid-operation\n' "$(date '+%Y-%m-%d %H:%M:%S')" >> "$LOG"
  exit 0
}

# Skip on detached HEAD
git symbolic-ref -q HEAD >/dev/null || {
  printf '%s [SKIP] detached HEAD\n' "$(date '+%Y-%m-%d %H:%M:%S')" >> "$LOG"
  exit 0
}

# Skip if user already has something staged (might be writing their own commit)
[ -n "$(git diff --cached --name-only)" ] && {
  printf '%s [SKIP] user has staged changes\n' "$(date '+%Y-%m-%d %H:%M:%S')" >> "$LOG"
  exit 0
}

git add Claude/

DIFFSTAT=$(git diff --cached --stat -- Claude/)
DIFFBODY=$(git diff --cached -- Claude/ | head -300)
RECENT=$(git log -5 --format='%s' -- Claude/)

PROMPT=$(cat <<EOF
Generate one conventional-commits message for the staged diff below in /Users/mian.yang/Repos/my-ai-agents.

Recent commit style from this repo (match this voice):
$RECENT

Format rules:
- Single line, <70 chars when possible
- <type>(<scope>): <lowercase description>
- Types: feat, fix, refactor, docs, chore, style, test, build, perf, ci, security
- Imperative mood, no trailing period
- Scope examples used here: hooks, scripts, settings, skills, agents, setup
- Output ONLY the message line — no quotes, no preamble, no markdown

Stat:
$DIFFSTAT

Diff (truncated to 300 lines):
$DIFFBODY
EOF
)

MSG=$(printf '%s' "$PROMPT" | claude --print --bare --no-session-persistence --model haiku 2>>"$LOG" \
  | head -1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | tr -d '`"')

# Validate: must be a conventional-commits line, not a generic "auto-sync"
if [ -z "$MSG" ] || \
   ! echo "$MSG" | grep -qE '^(feat|fix|refactor|docs|chore|style|test|build|revert|perf|ci|security)(\([a-z0-9_-]+\))?: [a-z]' || \
   echo "$MSG" | grep -qE 'auto-sync'; then
  printf '%s [ABORT] message did not pass validation: %s — un-staged, leaving for manual commit\n' \
    "$(date '+%Y-%m-%d %H:%M:%S')" "$MSG" >> "$LOG"
  git reset -q HEAD -- Claude/ 2>/dev/null
  exit 0
fi

if git commit -q -m "$MSG" 2>>"$LOG"; then
  SHA=$(git rev-parse --short HEAD)
  printf '%s [COMMIT] %s — %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$SHA" "$MSG" >> "$LOG"
else
  printf '%s [FAIL] git commit failed\n' "$(date '+%Y-%m-%d %H:%M:%S')" >> "$LOG"
fi
exit 0
